#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <io.h>
#include <fcntl.h>
#include <sys\stat.h>

typedef struct StringEntry {
	char *name;
	char *string;
	struct StringEntry *next;
} StringEntry;

typedef unsigned /*long*/ offset_t;	// as long as the string file is below 64k, we don't need long offsets

StringEntry *root=NULL, *last=NULL;

void Quit(char *error)
{
	puts(error);
	exit(1);
}

void *GetMem(size_t size)
{
	void *mem = malloc(size);
	if (!mem)
	{
		Quit("out of memory");
	}
	return mem;
}

void Write(int handle, void *buf, size_t size)
{
	if (write(handle, buf, size) != size)
		Quit("write error");
}

void AddStringEntry(char *name, char *string)
{
	StringEntry *e = GetMem(sizeof(StringEntry));
	e->next = NULL;
#if 0
	e->name = GetMem(strlen(name)+1);
	e->string = GetMem(strlen(string)+1);
	strcpy(e->name, name);
	strcpy(e->string, string);
#else
	// the strings are constants anyway, no need to waste memory on duplicates
	e->name = name;
	e->string = string;
#endif
	if (!last)
	{
		root = e;
		last = e;
	}
	else
	{
		last->next = e;
		last = e;
	}
}

void SaveStringFile(char *filename)
{
	int handle = open(filename, O_CREAT|O_WRONLY|O_TRUNC|O_BINARY, S_IFREG|S_IREAD|S_IWRITE);
	if (handle != -1)
	{
		offset_t offset = 0;
		StringEntry *e;

		// count the string entries to get the file offset of the first entry
		for (e = root; e; e=e->next)
		{
			offset += sizeof(offset);
		}
		offset += sizeof(offset);

		// write the offsets to the file
		for (e = root; e; e=e->next)
		{
			Write(handle, &offset, sizeof(offset));
			offset += strlen(e->string)+1;
		}
		Write(handle, &offset, sizeof(offset));

		// write the strings
		for (e = root; e; e=e->next)
		{
			Write(handle, e->string, strlen(e->string)+1);
		}

		close(handle);
	}
	else
	{
		char strbuf[80];
		strcpy(strbuf, "cannot open ");
		strcat(strbuf, filename);
		strcat(strbuf, " for writing!");
		Quit(strbuf);
	}
}

void SaveHeaderFile(char *filename)
{
	int handle = open(filename, O_CREAT|O_WRONLY|O_TRUNC|O_TEXT, S_IFREG|S_IREAD|S_IWRITE);
	if (handle != -1)
	{
		static char str1[] =
			"//\n"
			"// Generated by MakeStr - DO NOT MODIFY!\n"
			"//\n"
			"#ifndef __GAMESTR_H__\n"
			"#define __GAMESTR_H__\n"
			"\n"
			"typedef enum {\n\t";
		static char str2[] = 
			"NUMGAMESTRINGS\n"
			"} stringnames;\n"
			"\n"
			"#define MAXGAMESTRINGLENGTH ";
		static char str3[] =
			"\n"
			"\n"
			"#endif";
		static char str4[] = ",\n\t";

		unsigned maxlen = 0, len;
		StringEntry *e;
		char strbuf[20];

		Write(handle, str1, sizeof(str1)-1);

		for (e=root; e; e=e->next)
		{
			Write(handle, e->name, strlen(e->name));
			Write(handle, str4, sizeof(str4)-1);
			len = strlen(e->string)+1;
			if (len > maxlen)
				maxlen = len;
		}

		Write(handle, str2, sizeof(str2)-1);
		itoa(maxlen, strbuf, 10);
		Write(handle, strbuf, strlen(strbuf));
		Write(handle, str3, sizeof(str3)-1);

		close(handle);
	}
	else
	{
		char strbuf[80];
		strcpy(strbuf, "cannot open ");
		strcat(strbuf, filename);
		strcat(strbuf, " for writing!");
		Quit(strbuf);
	}
}

void main(void)
{
	//CK_GAME.C
	//AddStringEntry("S_CHECKPOINTFILE", "CHKPOINT.CKS");
	
	AddStringEntry("S_nil", "");	// let's make sure string number 0 is an empty string
	
	AddStringEntry("S_LOADGAME_NOMEM", "Not enough memory\nto load game!");

	AddStringEntry("S_YOUDIDNTMAKEITPAST", "You didn't make it past");
	AddStringEntry("S_TRYAGAIN", "Try Again");
	AddStringEntry("S_RESTARTFROMCHECKPOINT", "Restart from Checkpoint");
	AddStringEntry("S_EXITTOWORLDMAP", "Exit to Ancient Forest");
	AddStringEntry("S_CANTLOADCKECKPOINT", "can't load checkpoint");

	AddStringEntry("S_GAMEOVER", "Game Over!");
	AddStringEntry("S_RANOUTOFLIVES", "Looks like you ran out of lives!");
	// you can add hundreds of additional strings in here (string name doesn't matter!)
	AddStringEntry("S_OUTOFLIVES1", "Out of lives again?\nBummer!");
	AddStringEntry("S_OUTOFLIVES2", "Third time's the charm, right?");
	AddStringEntry("S_OUTOFLIVES3", "How to overthrow permadeath...");
	AddStringEntry("S_OUTOFLIVES4", "Welcome to the Game Over game.");
	AddStringEntry("S_RANOUTOFJOKES", "Looks like we ran out of jokes!");	// used as a marker (final entry in the list)
	AddStringEntry("S_CONTINUE", "Continue");
	AddStringEntry("S_QUIT", "Quit");

	AddStringEntry("S_CONTINUEJOKE1", "Continuing your game will cost\n\n$4.99\n\nPlease prepare to enter your\ncredit card information.");
	AddStringEntry("S_CONTINUEJOKE2", "Just kidding! You don't have to\npay any money to continue.\nWhat do you think this is?\nA mobile game!?\n\nWe'll just reset your score...");
	AddStringEntry("S_CONTINUEJOKE0", "");
	// you can add hundreds of additional strings in here (string name doesn't matter!)
	
	AddStringEntry("S_CONTINUEJOKE2A", "A bethetic.net account\nis required to play.\n\nPlease connect to the internet\nto continue.");
	AddStringEntry("S_CONTINUEJOKE2B", "Oh wait,\nwe already did that joke!\n\nNevermind. Move along,\nnothing to see here.");
	AddStringEntry("S_CONTINUEJOKE2C", "");

	AddStringEntry("S_CONTINUEJOKE3A", "You won't ever make it\nto the High Scores\nif you continue like this.\n\nMaybe choose another\ndifficulty level?");
	AddStringEntry("S_CONTINUEJOKE3B", "");
	
	AddStringEntry("S_CONTINUEJOKE4A", "I have the impression\nthat you are really stuck.\n\nWhy don't you take a break\nalready and try a little round\nof NomNom instead?");
	AddStringEntry("S_CONTINUEJOKE4B", "");
	
	AddStringEntry("S_CONTINUEJOKE5A", "Are you losing concentration?\nThis is your fifth Game Over\nin a row.\n\nNow, take a deep breath\nbefore you continue.");
	AddStringEntry("S_CONTINUEJOKE5B", "Resetting your score\nmight help you to gain focus.\n\n\nPress Enter\nwhenever you feel ready.");
	AddStringEntry("S_CONTINUEJOKE5C", "");

	AddStringEntry("S_CONTINUEJOKE6A", "\nSince you seem to be a\nhopeless case...\n\nHave you ever thought about\ncheating?");
	AddStringEntry("S_CONTINUEJOKE6B", "Hold down the F10 key and press\nthe letter G to enter God Mode.\nNow you can play the game\nwithout risking death.\nSure, this ruins the fun, but\nmaybe you like it that way...");
	AddStringEntry("S_CONTINUEJOKE6C", "");
	
	AddStringEntry("S_CONTINUEJOKE7A", "C'mon. Now you are playing\na different game, aren't you?!\n\nDo you really want to find out\nhow many different game over\ntexts I put in?");
	AddStringEntry("S_CONTINUEJOKE7B", "\nLet me put it this way:\n\n'Holmes, these aren't the droids\nyou're looking for.'");
	AddStringEntry("S_CONTINUEJOKE7C", "");
	
	AddStringEntry("S_CONTINUEJOKE8A", "\nWelcome to the metagame.\n\nThe goal of this game is\nto waste time with nonsense.");
	AddStringEntry("S_CONTINUEJOKE8B", "Why don't you try\nCtrl + F9\nfor once?\n\nThis should shortcut things\nfor all of us.");
	AddStringEntry("S_CONTINUEJOKE8C", "");
	
	AddStringEntry("S_CONTINUEJOKE9A", "\nStill here?\n\nLet me trick you a bit.\nThis time around\nI switched texts.");
	AddStringEntry("S_CONTINUEJOKE9B", "'Continue' actually quits\nand 'Quit' continues this\nlunatic nonsense.\n\nToo bad, you've chosen\nthe wrong input...");
	AddStringEntry("S_CONTINUEJOKE9C", "");
	
	AddStringEntry("S_CONTINUEJOKE10A", "A");
	AddStringEntry("S_CONTINUEJOKE10B", "A  B");
	AddStringEntry("S_CONTINUEJOKE10C", "A  B  C");
	AddStringEntry("S_CONTINUEJOKE10D", "A  B  C\n1");
	AddStringEntry("S_CONTINUEJOKE10E", "A  B  C\n1  2");
	AddStringEntry("S_CONTINUEJOKE10F", "A  B  C\n1  2  3");
	AddStringEntry("S_CONTINUEJOKE10G", "A  B  C\n1  2  3\nyou");
	AddStringEntry("S_CONTINUEJOKE10H", "A  B  C\n1  2  3\nyou belong");
	AddStringEntry("S_CONTINUEJOKE10I", "A  B  C\n1  2  3\nyou belong to me");
	AddStringEntry("S_CONTINUEJOKE10Q", "");
	
	AddStringEntry("S_CONTINUEJOKE11A", "\n...\n\nWelcome to the limbo!");	
	AddStringEntry("S_CONTINUEJOKE11B", "");
	
	AddStringEntry("S_FINALCONTINUEJOKE", "");	// used as a marker, should be an empty string!
	/*
		max text string length:
	|<----------------------------->|
	 
	 
	 * barmy future things:	 
		
	AddStringEntry("S_CONTINUEJOKE19", "Did your hand slip\non the keyboard?\n\n\nYou want to play a game,\nso let's play a game...");

	AddStringEntry("S_CONTINUEJOKE20", "You won!\n\nI quit.\n\nI hope you are satisfied.\nNow go and press quit. ");
	AddStringEntry("S_CONTINUEJOKE21", "endif {\nUS_PrintCentered('Quitting...');\nfontcolor = F_BLACK;\nVW_UpdateScreen();\nQuit(nil);}");	
	 
	AddStringEntry("S_CONTINUEJOKE22", "Your code is:\n\nN2GG-N0OB-I5UK-314-5UY7\n\nReport it to K1n9_Duk3\nand win a prize!");				 
	*/
	AddStringEntry("S_DEMO", "DEMO");
	AddStringEntry("S_RECORDDEMO", "  Record a demo from level (0-17): ");
	AddStringEntry("S_DEMOFILE", "DEMO?.CKS");
	AddStringEntry("S_SAVEDEMO", " Save as demo no(0-9):");
	AddStringEntry("S_CANNOTWRITEDEMO", "EndDemoRecord: Cannot write demo file!");

	AddStringEntry("S_LOADLEVEL_NOMEM", "Insufficient memory\nto load level!");
	AddStringEntry("S_LOADWORDLMAP_NOMEM", "GameLoop: Insufficient memory to load world map!");
	AddStringEntry("S_ONEMOMENT", "One Moment");

	//CK_PLAY.C
	AddStringEntry("S_LOCATION", "LOCATION");
	AddStringEntry("S_SCORE", "SCORE");
	AddStringEntry("S_EXTRA", "EXTRA");
	AddStringEntry("S_LEVEL", "LEVEL");
	AddStringEntry("S_CHEATER", "CHEATER!");
	AddStringEntry("S_EASY", "Easy");
	AddStringEntry("S_NORMAL", "Normal");
	AddStringEntry("S_HARD", "Hard");
	AddStringEntry("S_KEYS", "KEYS");
	AddStringEntry("S_AMMO", "AMMO");
	AddStringEntry("S_KEENS", "KEENS");
	AddStringEntry("S_DROPS", "DROPS");
	AddStringEntry("S_GOODIES", "GOODIES");
	AddStringEntry("S_ITEMSDETECTED", "ITEMS DETECTED NEARBY:");
	AddStringEntry("S_POINTS", "POINTS");
	AddStringEntry("S_LIVES", "LIVES");

	AddStringEntry("S_DEBUGKEYSACTIVE", "Debug keys active");

	AddStringEntry("S_ACTIVEOBJECTS", " Active Objects: ");
	AddStringEntry("S_INACTIVEOBJECTS", "\n Inactive Objects: ");
	AddStringEntry("S_OBJECTSTOTAL", "\n Objects Total: ");
	AddStringEntry("S_SPRITESUSED", "\n Sprites Used: ");
	AddStringEntry("S_SPRITESFREE", "\n Sprites Available: ");
/*
	AddStringEntry("S_MEMUSAGE", "Memory Usage\n------------");
	AddStringEntry("S_MEMTOTAL", "Total:");
	AddStringEntry("S_MEMFREE", "\nFree:");
	AddStringEntry("S_WITHPURGE", "\nWith purge:");
	AddStringEntry("S_MEMUSED", "\nUsed:");
*/
	//Nisaba patch:
	AddStringEntry("S_MEMUSAGE", "Memory Usage\n------------");
	AddStringEntry("S_MEMTOTAL", "Bytes Total:");
	AddStringEntry("S_MEMFREE", "\nBytes Free:");
	AddStringEntry("S_WITHPURGE", "\nWith purge:");
	AddStringEntry("S_MEMUSED", "\nBytes Used:");
	AddStringEntry("S_BLOCKSFREE", "\nBlocks Free:");

	AddStringEntry("S_FREEITEMS", "Free items!");

	AddStringEntry("S_WORKING", "WORKING");

	AddStringEntry("S_WALLDEBUGEASTWALL", "WallDebug: East wall > 2:");
	AddStringEntry("S_WALLDEBUGWESTWALL", "WallDebug: West wall > 2:");

	AddStringEntry("S_MAPHEADFILE", "MAPHEAD.CKS");

	AddStringEntry("S_SPRITETEST", "Sprite Test\n-----------");
	AddStringEntry("S_SPRITETESTSTUFF", "Sprite:\nWidth:\nHeight:\nOrgx:\nOrgy:\nXl:\nYl:\nXh:\nYh:\nShifts:\nMem:\n");
	AddStringEntry("S_SHIFT", "Shift:");
	AddStringEntry("S_NEWLINE", "\n");

	AddStringEntry("S_SOUNDTEST", "Sound Test\n-----------");
	AddStringEntry("S_SOUNDNUM", "Sound:\n");

	AddStringEntry("S_BORDERCOLOR", "  Border color (0-15): ");
	AddStringEntry("S_GODMODE_OFF", "God mode OFF");
	AddStringEntry("S_GODMODE_ON", "God mode ON");
	AddStringEntry("S_JUMPCHEAT_ON", "Jump cheat ON");
	AddStringEntry("S_JUMPCHEAT_OFF", "Jump cheat OFF");
	AddStringEntry("S_NOCLIP_ON", "No clipping ON");
	AddStringEntry("S_NOCLIP_OFF", "No clipping OFF");
	AddStringEntry("S_SLOMO_ON", "Slow motion ON");
	AddStringEntry("S_SLOMO_OFF", "Slow motion OFF");
	AddStringEntry("S_EXTRAVBLS", "  Add how many extra VBLs(0-8):");
	AddStringEntry("S_LEVELWARP", "  Warp to which level (0-17): ");

	AddStringEntry("S_PAUSED", "PAUSED");

	AddStringEntry("S_OBJARRAYFULL", "GetNewObj: No free spots in objarray!");
	AddStringEntry("S_REMOVEPLAYER", "RemoveObj: Tried to remove the player!");

	AddStringEntry("S_BADMUSIC", "StartMusic() - bad level number");
	AddStringEntry("S_MUSIC_NOMEM", "Insufficient memory\nfor background music!");

	//CK_KEEN.C
	AddStringEntry("S_BADKEYHOLDERSPOT", "Keyholder points to a bad spot!");
	AddStringEntry("S_BADSHOTDIR", "SpawnShot: Bad dir!");

	//CK_MAIN.C
	/*
	AddStringEntry("S_NOTENOUGHMEMORY1", "There is not enough memory available to play the game reliably.  You can");
	AddStringEntry("S_NOTENOUGHMEMORY2", "play anyway, but an out of memory condition will eventually pop up.  The");
	AddStringEntry("S_NOTENOUGHMEMORY3", "correct solution is to unload some TSRs or rename your CONFIG.SYS and");
	AddStringEntry("S_NOTENOUGHMEMORY4", "AUTOEXEC.BAT to free up more memory.\n");
	AddStringEntry("S_NOTENOUGHMEMORY5", "Do you want to (Q)uit, or (C)ontinue?");

	AddStringEntry("S_DEMOLOOPEXITED", "Demo loop exited!?");
	*/
	// Nisaba patch
	AddStringEntry("S_HELP1" ,"HELP");
	AddStringEntry("S_HELP2", "H");
	AddStringEntry("S_HELP3", "?");
	// do NOT change the order of these strings:
	AddStringEntry("S_HELPTEXT1",  "FORAY IN THE FOREST -- Version 0.102.3x -- String File: " __DATE__ " - " __TIME__);
	AddStringEntry("S_HELPTEXT2",  "\nSupported parameters:\n");
	AddStringEntry("S_HELPTEXT3",  " NOEMS      - disable checking for EMS memory");
	AddStringEntry("S_HELPTEXT4",  " NOXMS      - disable checking for XMS memory");
	AddStringEntry("S_HELPTEXT5",  " NOUMB      - disable high memory allocation");
	AddStringEntry("S_HELPTEXT6",  " NOJOYS     - disable joystick detection");
	AddStringEntry("S_HELPTEXT7",  " NOMOUSE    - disable mouse detection");
	AddStringEntry("S_HELPTEXT8",  " NOBORDER   - disable colored overscan borders");
	AddStringEntry("S_HELPTEXT9",  " HIDDENCARD - override video card detection, set EGA card");
	AddStringEntry("S_HELPTEXT9A", " VGA        - override video card detection, set VGA card");
	AddStringEntry("S_HELPTEXT10", " COMP       - enable SVGA compatibility mode");
	AddStringEntry("S_HELPTEXT11", " NOCOMP     - disable SVGA compatibility mode");
	AddStringEntry("S_HELPTEXT12", " JERK       - enable jerky motion fix");
	AddStringEntry("S_HELPTEXT13", " NOAL       - disable AdLib detection");
	AddStringEntry("S_HELPTEXT14", " ADLIB      - override AdLib detection");
	AddStringEntry("S_HELPTEXT15", " OPLPORT x  - change OPL port address (for OPL2LPT / OPL3LPT devices)");
	AddStringEntry("S_HELPTEXT16", "              'x' is port address in hex.  Example: OPLPORT 3BC");
	AddStringEntry("S_HELPTEXTEND"," HELP       - show this list");	// marks the end of the help text strings
	// (Note: only the names S_HELPTEXT1 and S_HELPTEXTEND will be used directly by the game code, the names for the other strings don't matter)
	
	AddStringEntry("S_NOTENOUGHMEMORY1",  "There is not enough memory available to play the game reliably.  The correct");
	AddStringEntry("S_NOTENOUGHMEMORY2",  "solution is to free up as much conventional and high memory as possible by");
	AddStringEntry("S_NOTENOUGHMEMORY3",  "installing an EMS emulator or Upper-Memory-Block manager, loading DOS high, and");
	AddStringEntry("S_NOTENOUGHMEMORY4",  "unloading any CD-ROM or network drivers and TSRs.\n");
	AddStringEntry("S_NOTENOUGHMEMORY5",  "You can play anyway, but an out of memory condition will eventually pop up.\n");
	AddStringEntry("S_NOTENOUGHMEMORYEND","Do you want to (Q)uit, or (C)ontinue?");
	// (Note: only the names S_NOTENOUGHMEMORY1 and S_NOTENOUGHMEMORYEND will be used directly by the game code, the names for the other strings don't matter)

	AddStringEntry("S_DEMOLOOPEXITED", "Demo loop exited!?");

	//CK_MISC.C
	AddStringEntry("S_BADCLOUDSTART", "Cloud start without cloud end!");
	AddStringEntry("S_BADCLOUDEND", "Cloud end without cloud start!");

	AddStringEntry("S_LEVELNAME0", "Ancient Forest");
	AddStringEntry("S_LEVELNAME1", "BwB Megarocket");
	AddStringEntry("S_LEVELNAME2", "The Deciduous Forest");
	AddStringEntry("S_LEVELNAME3", "The Outpost");
	AddStringEntry("S_LEVELNAME4", "Secret Reservoir");
	AddStringEntry("S_LEVELNAME5", "Spiky Village");
	AddStringEntry("S_LEVELNAME6", "Troubled Water");
	AddStringEntry("S_LEVELNAME7", "Lost Mine");
	AddStringEntry("S_LEVELNAME8", "Donut Dome");
	AddStringEntry("S_LEVELNAME9", "Fawlty Towers"); // Fatty Owls, Flowery Twats, Warty Towels, Flay Otters, Farty Towels,
	AddStringEntry("S_LEVELNAME10", "Asparagus Roots");
	AddStringEntry("S_LEVELNAME11", "Habitatio\nPiscum Swimeatum");	// Three-Tooth Cavern
	AddStringEntry("S_LEVELNAME12", "Manara Samarra");
	AddStringEntry("S_LEVELNAME13", "Shilin Forest");
	AddStringEntry("S_LEVELNAME14", "The Concealed Ruin");
	AddStringEntry("S_LEVELNAME15", "The Pyramid of Doors");
	AddStringEntry("S_LEVELNAME16", "The Magic Forest");
	AddStringEntry("S_LEVELNAME17", "S}vng{ngernes Skov");	// Søvngængernes Skov = Sleepwalkers Forest
	AddStringEntry("S_LEVELNAME18", "Temple of Doom");
	AddStringEntry("S_LEVELNAME19", "Slugidarium");
	AddStringEntry("S_LEVELNAME20", "Donut Heaven");
	AddStringEntry("S_LEVELNAME21", "The High Scores");
	AddStringEntry("S_LEVELNAME22", "The Magic Forest");
	AddStringEntry("S_LEVELNAME23", "Le TARDIS");
	AddStringEntry("S_LEVELNAME24", "Top Secret\nACME Inc. Laboratory");
	AddStringEntry("S_LEVELNAME25", "Cloudy Cliff");
//	AddStringEntry("S_LEVELNAME26", "TEST");

	AddStringEntry("S_LEVELTEXT0", "Keen wanders the\nAncient Forest");
	AddStringEntry("S_LEVELTEXT1", "Keen launches into the\nBwB Megarocket");
	AddStringEntry("S_LEVELTEXT2", "Keen sways through\nSukkahs and\ndeciduous trees"); 
	AddStringEntry("S_LEVELTEXT3", "Keen warily\ninvestigates\nthe Outpost");
	AddStringEntry("S_LEVELTEXT4", "Keen inquisitively\ndescends to the\nSecret Reservoir");
	AddStringEntry("S_LEVELTEXT5", "Keen boldly searches\nthe Spiky Village");
	AddStringEntry("S_LEVELTEXT6", "Keen crosses over\nTroubled Water");
	AddStringEntry("S_LEVELTEXT7", "Keen braces himself\nfor the Lost Mine");
	AddStringEntry("S_LEVELTEXT8", "Keen enters the\nDonut Dome\nin awe");
	AddStringEntry("S_LEVELTEXT9", "Keen takes delight\nin a series of\nFawlty Towers");
	AddStringEntry("S_LEVELTEXT10", "Keen swings by\nthe Asparagus Roots");
	AddStringEntry("S_LEVELTEXT11", "Keen plummets into\nthe Habitatio\nPiscum Swimeatum");
	AddStringEntry("S_LEVELTEXT12", "Keen bravely ascends\nManara Samarra");
	AddStringEntry("S_LEVELTEXT13", "Keen vaults through\nthe Shilin Forest");
	AddStringEntry("S_LEVELTEXT14", "Keen unearths\na Concealed Ruin");
	AddStringEntry("S_LEVELTEXT15", "Keen discovers\nthe forgotten\nPyramid of Doors");
	AddStringEntry("S_LEVELTEXT16", "Keen finds himself\nin the twilight of\nthe Magic Forest");
	AddStringEntry("S_LEVELTEXT17", "Keen sights relicts\nin the Skov af\nS}vng{ngere");	// Skov af Søvngængere = Forest of Sleepwalkers
	AddStringEntry("S_LEVELTEXT18", "Keen stealthy\nwarps through the\nTemple of Doom");
	AddStringEntry("S_LEVELTEXT19", "Keen follows a\nsecret slime trail\nto the Slugidarium");
	AddStringEntry("S_LEVELTEXT20", "Princess Lindsey\ntakes Keen to\nDonut Heavens");
	AddStringEntry("S_LEVELTEXT21", "Keen unexplainedly\ndetects\nthe High-Scores");
	AddStringEntry("S_LEVELTEXT22", "Keen strays\neven deeper into\nthe Magic Wonderland");
	AddStringEntry("S_LEVELTEXT23", "Keen rematerialises\nthrough\ntime and space");
	AddStringEntry("S_LEVELTEXT24", "Keen discovers\nthe top secret\nACME Inc. Laboratory");
	AddStringEntry("S_LEVELTEXT25", "Keen bravely\nhops along a\nCloud-Covered Cliff");
//	AddStringEntry("S_LEVELTEXT26", "Keen enters\nLevel 26");

	// special level messages
	AddStringEntry("S_LEVELTEXTAPPROACH", "Keen approaches the\nAncient Forest");
	AddStringEntry("S_LEVELTEXTLAND", "Keen lands in the\nAncient Forest");
	AddStringEntry("S_LEVELTEXTBONUSDONE", "Om nom nom...");
	
	/*	max text string length:
	|<----------------------------->|
	
	 The Janitor appears in level 2, 4, 8, 9, 11, 14, 15, and 24 (4x). */
	// Level 2	Deciduous Forest 
	AddStringEntry("S_JANITORMESSAGE0", "By the Secrets of the\nArmageddon Babysitter!\nAren't you\nthat kiddo from\nThe Earth Must Mars?");
	AddStringEntry("S_JANITORMESSAGE1", "I'm the emissary of the\nIntergalactic Janitorial\nService of Your Trust.\nYour planet\nneeds a makeover?\nWe beam & clean!");
	AddStringEntry("S_JANITORMESSAGE2", "If I find\nany joy sparking\nsentimental items,\nI'll bring them to your\ntin can spaceship.");
	// Level 4	Life Water Oasis
	AddStringEntry("S_JANITORMESSAGE3", "I'm just fulfilling\nthe service booked\nby a certain Mr. Em\nof de-cluttering this\nplanet, which is more\nwork than you'd think.");
	AddStringEntry("S_JANITORMESSAGE4", "Sonny, that might work\nfor bread crumbs,\nbut Slug Slime is not\nso easy to clean up.");
	// Level 8	Donut Dome
	AddStringEntry("S_JANITORMESSAGE5", "Can you believe it?\nSlug slime at every turn.\nIt's dangerous after all\n\n*sigh*");
	AddStringEntry("S_JANITORMESSAGE6", "While on the subject:\n\nChoose your babysitter\ncarefully, young fellow!");
	// Level 9	Falty Towers	
	AddStringEntry("S_JANITORMESSAGE7", "I have seen the future.\nYou will have two kids,\nand you'll name them\nBilly and Billie.");
	// Level 11	Dopefish
	AddStringEntry("S_JANITORMESSAGE8", "Ggoh thig you sogh mg\nfgor regscuing mgge!\nI'gll regur tgo the\nGracle chagber\nigmmediatggely. Blub.");
	// Level 14	Pyramid Mummy
	AddStringEntry("S_JANITORMESSAGE9", "This really is a\nramshackle warehouse.\nTime to take\na clean sweep.");
	// Level 15	Pyramid of doors		
	AddStringEntry("S_JANITORMESSAGE10", "Close the door\nbefore you track\nmore dust in here.\nThis place took\nforever to tidy."); 
	AddStringEntry("S_JANITORMESSAGE11", "This is actually the\nentrance here.\nExit through the gift\nshop, which is where\nyou just came from.");
	// Level 24.1	Cloning Lab
	AddStringEntry("S_JANITORMESSAGE12", "...liquids, chemicals,\napparatus... ");
	AddStringEntry("S_JANITORMESSAGE18", "...this must be\na laboratory!\n\nOne should clean here\nparticularly thoroughly.");
	AddStringEntry("S_JANITORMESSAGE19", "They said there would\nbe Pages to support.\nBut they turned out\nto be totally useless\nunless you control\n their every move.");
	// Level 24.2	
	AddStringEntry("S_JANITORMESSAGE13", "The Life-Changing Magic\nof tidying up would go\nso much faster in coop,\nbut good staff is\nhard to find these days.");
	AddStringEntry("S_JANITORMESSAGE14", "*sigh*"); 
	AddStringEntry("S_JANITORMESSAGE20", "If only I knew where\nthose planet denizens\nhave their nest...\n\nThey seem to\nmultiply incessantly."); 
	// Level 24.3
	AddStringEntry("S_JANITORMESSAGE15", "Don't dream your life,\nlive your dreams."); 
	AddStringEntry("S_JANITORMESSAGE16", "In life it's crucial to\nchoose the right path,\nyoung fellow."); 
	// Level 24.4
	AddStringEntry("S_JANITORMESSAGE17", "...true,\nheadquarters advertised\nit as a one-man job,\n but a little support\nwouldn't hurt.");
	
	// REPLY
	// Level 2	Deciduous Forest
	AddStringEntry("S_JANITORREPLY0", "Sure gramps...\nand Aliens Ate My Toast.\n\nWhy are you scrubbing\nthis ancient statue?");
	AddStringEntry("S_JANITORREPLY1", "...interesting...\n\nYou haven't seen my\nfriends by any chance?\nSome nasty, sneaky\nvillain kidnapped them.");
	// Level 4	Life Water Oasis		
	AddStringEntry("S_JANITORREPLY2", "You again?");
	AddStringEntry("S_JANITORREPLY3", "Why not use a vac?\nI'd have one on my BwB.\n\nLook, my mom used\nthat thing for years.");
	// Level 8	Donut Dome
	AddStringEntry("S_JANITORREPLY4", "Molly makes the\nworld's second\nbiggest sandwiches.\nThey give me\nthe munchies.");
	// Level 9	Falty Towers	
	AddStringEntry("S_JANITORREPLY5", "I may not have the\nhighest IQ in the\nuniverse, but I'm\nnot THAT stupid!");
	// Level 11	Dopefish
	AddStringEntry("S_JANITORREPLY6", "Wise plan of action,\nyour ancientness.\n\nSwim swim hungry,\n sweem sweem hungry.");
	// Level 14	Pyramid Mummy
	AddStringEntry("S_JANITORREPLY7", "I see!  Here is where\nall that toilet paper\nvanishes to.\nGood to know in\n case of a pandemic.");
	// Level 15	Pyramid of doors
	AddStringEntry("S_JANITORREPLY8", "Now don't tell me\nyou have the\nmaster keys\nto shortcut\nthis maze.");
	AddStringEntry("S_JANITORREPLY9", "...");
	// Level 24.1 Cloning Lab
	AddStringEntry("S_JANITORREPLY10", "Yo, Janitor man!\n\nWhat's cooking?"); 
	AddStringEntry("S_JANITORREPLY15", "...and fancy machines\nwith galactic beams..."); 
	// Level 24.2
	AddStringEntry("S_JANITORREPLY11", "Is there actually\nany place you\nhaven't been?");
	// Level 24.3
	AddStringEntry("S_JANITORREPLY12", "Listen to this,\nnow he is giving\ngalactic oracle sayings.\nWhat comes next?");
	AddStringEntry("S_JANITORREPLY13", "That'd be building a\nclassic computer game\nin which an 8-year-old\ngenius pours heaps of\nsugar down his throat\nWait... what!?");
	// Level 24.4
	AddStringEntry("S_JANITORREPLY14", "...mmm...\n\nI wonder\nwhat this machine\nis good for.");
	
	// Jokes:
	AddStringEntry("S_JANITORJOKE0", "Jamais vu.\nHow eerie...");
	AddStringEntry("S_JANITORJOKE1", "Remember to not disturb\nthe great sea serpent.\nIt's a little shy and\ntends to bite a wee bit");	// A bit?\nIt is a savage, naughty,\naquatic beast with a\npassion for football\nhelmets.	// You don't have a\nneoprene with you,\ndo you?
	AddStringEntry("S_JANITORJOKE2", "What did I\nwant to say again?\nAh, of course...");	
	AddStringEntry("S_JANITORJOKE3", "It's you again... I always\nwondered if there was\nlife after death. Thank\nyou for clearing that up\nAnyway, as I was\nsaying...");
	AddStringEntry("S_JANITORJOKE4", "Gropefigsh ghdreamgs.\nBlub.");
	AddStringEntry("S_JANITORJOKE5", "Look out!\nNeither the ceiling\nnor the floor\nappear to be stable.\n...oh well...");
	AddStringEntry("S_JANITORJOKE6", "Time is nature's way\nof keeping everything\nfrom happening at once.\n\nWhat was it I intended\nto say again...?");
	AddStringEntry("S_JANITORJOKE7", "Subscribe to my\nSunTube channel,\nfollow me on Instagalaxy\nTwitverse & Craterbook\nsupport me @ Patremoon\nbrowse my Planetsy shop");
	AddStringEntry("S_JANITORJOKE8", "We have the right\nto random speech.\n\nWhat was it I intended\nto say again...?");
	AddStringEntry("S_JANITORJOKE9", "According to the\nunix timestap,\n2038 will be\nthe End of Time");
	AddStringEntry("S_JANITORJOKE10", "A B C\n1 2 3\nYou\nbelong\nto\nme!");

	// Monologs:
	AddStringEntry("S_JANITORMONOLOG0", "\"Some clean,\nothers dream...\"\n\n*sigh*");
	AddStringEntry("S_JANITORMONOLOG1", "\"Don't bother getting up\nor moving out\nof my way.\"\n\n...Kids these days...");
	AddStringEntry("S_JANITORMONOLOG2", "Time flies like an arrow;\nfruit flies like a banana.\n\n");
	AddStringEntry("S_JANITORMONOLOG3", "Be careful not to do\n your good deeds\nwhen there's no one\nwatching you.");
	AddStringEntry("S_JANITORMONOLOG4", "80% of success\nis showing up.");
	AddStringEntry("S_JANITORMONOLOG5", "Deja reve?\n\n\n");
	AddStringEntry("S_JANITORMONOLOGEND", "");	// used as a marker, must follow after last monolog string

	AddStringEntry("S_JANITORSTUNNEDMSG0", "Dizzy spell?\nYou've got to eat\nyour vegetables,\ndo you hear me?");

	AddStringEntry("S_JANITORNISASIMESSAGE0", "By the monolith\nof knowledge:\nis that really fashionable\nfor you youngsters?");
	AddStringEntry("S_JANITORNISASIREPLY0", ".niarb ym fo\nsnoitulovnoc eht tuoba\nselbbarcs ssensuoicsnoc\nrehgih a ekil smeeS");
	
	// Lindsey
	AddStringEntry("S_LINDSEYMESSAGE0", "Welcome to\nDonut Heavens!\nWe have cream and\ncustard fillings\ntopped with sprinkles.\nGo Catch 'Em All!");
	AddStringEntry("S_LINDSEYMESSAGE1", "If you ever wondered:\nIt was I\nwho embellished\nGnosticus #\nwith candies.");
	AddStringEntry("S_LINDSEYMESSAGE2", "I wonder\nwhere you stashed\nall the donuts?");
	AddStringEntry("S_LINDSEYMESSAGE3", "If you like collecting,\ndon't miss out on\ngetting hold of all 17\ncans of Slug Slime Soda\n\"Feeling sluggish? Slick\nsip & you won't slip!\"");

	AddStringEntry("S_LINDSEYREPLY0", "... and a giggly\nfairground\nbooth sound.\nThis must be heaven!");
	AddStringEntry("S_LINDSEYREPLY1", "Collecting all\nthose baby teeth\nunderneath my pillow\nfinally paid off.");
	AddStringEntry("S_LINDSEYREPLY2", "I jlmmpft flfff,\nflath anpf mmmph\nblahgggghspf...");
	
	// HAL
	AddStringEntry("S_HALMESSAGE1", "HAL, do you read me?");
	AddStringEntry("S_HALREPLY1", "BOTB TROF TFOS\nMPP STQS\nKMTM\nAR OO AB\nORBK");
	AddStringEntry("S_HALMESSAGE2", "HAL, do you read me?\nOpen the Gates HAL");
	AddStringEntry("S_HALREPLY2", "I'm afraid\nI can't do that, Billy");
	
	// Spaceman Spiff Hint Sheet
	AddStringEntry("S_SPACEMANSPIFFMESSAGE1", "Spaceman Spiff says:\n\nIt's a magical world,\nBilly, ol' buddy...\nlet's go exploring!");
	AddStringEntry("S_SPACEMANSPIFFMESSAGE2", "Take this exclusive\ngrand space list for the\ninterplanetary explorer\nextraordinaire\nto spot the outermost\nreaches of the planet!");
	AddStringEntry("S_SPACEMANSPIFFMESSAGE3", "* Tardis: where time has no meaning\n* Salamander: wait for it... wait for it...\n* BwB: Radio, Plushies, Cans, Secret Area\n* Coin-op cabinets of galactic splendor\n\n* Where's Waldo? And where's Levellass?! \n* More hidden gems:  Racoon, Bunny, Squirrl,\n  The Blue Bird's club, Calvin&Hobbes, Dinu'u,\n Lemonshark, Tarsier, Tikk, HAL, Vool, E.T.\n\n* Find all six(+) special ending sequences:\n  hunt 100% or go on an anti-sweets diet, \n  and if you have to cheat, just remember: \n A failed mission is where the fun begins!\n\n* Also, always chat with the janitor twice.");
	
	// FOOBS.C
	AddStringEntry("S_INSPACE", "IN SPACE!");
	AddStringEntry("S_INSERTCOIN", "*** INSERT COIN ***");
	
	// S_MISC MESSAGES
	// do NOT change the order of these strings:
	AddStringEntry("S_MISCMESSAGE4", "I am not going to\ntouch that!");
	AddStringEntry("S_MISCMESSAGE5", "Out of order!");
	AddStringEntry("S_MISCMESSAGE6", "This looks familiar.\nI have seen\nthis before...");
	AddStringEntry("S_MISCMESSAGE7", "Stained wood\ndirectional arrows,\nhow convenient.");
	AddStringEntry("S_MISCMESSAGE8", "Aha,\nthis seems to be\nthe way to go.");
	AddStringEntry("S_MISCMESSAGE9", "I'm glad they put\nsigns everywhere.");
	AddStringEntry("S_MISCMESSAGE10", "... and now\nthis way around...");
	AddStringEntry("S_MISCMESSAGE11", "It seems\nas if something\nimportant is up there.\nI wonder\nwhat it could be.");
	AddStringEntry("S_MISCMESSAGE12", "Holy cripes on toast\nwith chocolate jimmies\nand a lobster bib!\nNow this is indeed the\nSecond Biggest Donut\nI've ever seen.");
	AddStringEntry("S_MISCMESSAGE13", "... coral-dorable...");
	AddStringEntry("S_MISCMESSAGE14", "By the sacred creature\nfrom the Black Slugoon!\nIs this the secret\nslug cult everyone\nis talking about?");
	AddStringEntry("S_MISCMESSAGE15", "Holy knuckle-cracking\nkringles with a sack\nfull of ketchup-covered\ncheese logs!\nIt's Count Slugula!");
	AddStringEntry("S_MISCMESSAGE16", "Blessed Scuba Slug\non an ancient stele\nwith sleek\ndiving goggles,\nhear my prayers!");
	AddStringEntry("S_MISCMESSAGE17", "Salute,\nCommander Slime,\ndefender of the\nSlugiverse.");
	AddStringEntry("S_MISCMESSAGE18", "Sweet mother of\nall good things\nand abundance!\nSpare me from the\nWicked Slug Witch.");
	AddStringEntry("S_MISCMESSAGE19", "Slug-Life!");
	AddStringEntry("S_MISCMESSAGE20", "By the Holy Ghost Slug\nand Lord Slugcula!\nIs that a pool full of\nslug slime?");
	AddStringEntry("S_MISCMESSAGE21", "Yeah, that's a\ndoughnut shell.\n\nSnailed it!");
	AddStringEntry("S_MISCMESSAGE22", "I know\nhow to read signs...\n\n... um...");
	AddStringEntry("S_MISCMESSAGE23", "Piscus Swimeatus.");
	AddStringEntry("S_MISCMESSAGE24", "Pink.\nMutant.\nAnd full of\ntoxic sludge.");
	AddStringEntry("S_MISCMESSAGE25", "A violent, impulsive\nand indulgent\nin the extreme\nwhite-furred anthro\n\"rabbity-thing\".");
	AddStringEntry("S_MISCMESSAGE26", "A rare and as yet\nunder-researched\nspecimen of the\nVool breed.");
	AddStringEntry("S_MISCMESSAGE27", "Nisawho?");
	AddStringEntry("S_MISCMESSAGE28", "Never ask a starfish\nfor directions...");
	AddStringEntry("S_MISCMESSAGE29", "Shell yeah!");
	AddStringEntry("S_MISCMESSAGE30", "A fully functional\ntype B socket\nthat supplies a\nmind-belt 2.0\nmachine cabinet\nwith sufficient power.");
	
	//|<----------------->|
	/*...*/
	AddStringEntry("S_MISCMESSAGEEND", "");	// used as a marker, should be an empty string!
	// (Note: only the names S_MISCMESSAGE4 and S_MISCMESSAGEEND will be used directly by the game code, the names for the other strings don't matter)
	
	// Radio message
	AddStringEntry("S_RADIOMESSAGE1", "Beep Bloop\nBlop Bleep Boop");
	
	// JUKEBOX
	AddStringEntry("S_JUKEBOXTOP", "Explore the planet to unlock\nthe full soundtrack.");
	AddStringEntry("S_JUKEBOXBOTTOM", "Select song: press Left/Right\nPlay song: press Enter    \nBack out: press Esc      ");
	
	// Song list -- do NOT change the order of these strings!
	AddStringEntry("S_MUSICNAME0", "Keenish Tune (kvee rmx)\nby\ntroublesomekeen");	// L1
	AddStringEntry("S_MUSICNAME1", "Commercials\nby\nKohntarkosz_");		// Level 1a)
	AddStringEntry("S_MUSICNAME2", "The Lady is Frightful\nby\nMOM4Evr");	// L2
	AddStringEntry("S_MUSICNAME3", "Nitelite\nby\nMr.M");					// L3
	AddStringEntry("S_MUSICNAME4", "Oasis\nby\nkvee");						// Level 4a)
	AddStringEntry("S_MUSICNAME5", "Jazzin' Them Nazis\nby\nBobby Prince");	// L5
	AddStringEntry("S_MUSICNAME6", "Guess\nby\nBobby Prince");				// L6
	AddStringEntry("S_MUSICNAME7", "Algeria\nby\nMOM4Evr");					// L7
	AddStringEntry("S_MUSICNAME8", "JazzK (kvee rmx)\nby\nunknown composer");// L8
	AddStringEntry("S_MUSICNAME9", "Fonk\nby\neggs_box");					// L9
	AddStringEntry("S_MUSICNAME10", "2Hot\nby\nkvee");						// Level 10a)
	AddStringEntry("S_MUSICNAME11", "SpoopS\nby\neggs_box");				// L11
	AddStringEntry("S_MUSICNAME12", "Education\nby\nMr.M");					// L12
	AddStringEntry("S_MUSICNAME13", "Tropic Pants\nby\nKohntarkosz_");		// L13
	AddStringEntry("S_MUSICNAME14", "A Very Special Pyramid\nby\neggs_box");// L14
	AddStringEntry("S_MUSICNAME15", "Funk 'Til Ya Red\nby\neggs_box");		// Level 15a)
	AddStringEntry("S_MUSICNAME16", "Icy F 10rppq (Nisaba rmx)\nby\nkvee");	// Level 16a)
	AddStringEntry("S_MUSICNAME17", "As Above...\nby\neggs_box");			// Level 17a)
	AddStringEntry("S_MUSICNAME18", "Colder\nby\nGridlock");				// L18
	AddStringEntry("S_MUSICNAME19", "Strut\nby\nKohntarkosz_");				// L19
	AddStringEntry("S_MUSICNAME20", "Kick Keen\nby\nTMST");					// L20
	AddStringEntry("S_MUSICNAME21", "Summerbeach\nby\nunknown composer");	// HighScores
	AddStringEntry("S_MUSICNAME22", "Midnight\nby\nkvee");					// Level 23
	AddStringEntry("S_MUSICNAME23", "Cruise\ntaken from\nThe Incredible Machine");	// End Win
	AddStringEntry("S_MUSICNAME24", "Slowasis\nby\nkvee");					// Level 4b)
	AddStringEntry("S_MUSICNAME25", "Fusion\ntaken from\nThe Incredible Machine");	// End Perfect
	AddStringEntry("S_MUSICNAME26", "Dopefish Jaws\nby\nLee Jackson");		// End Bad
	AddStringEntry("S_MUSICNAME27", "...So Below\nby\neggs_box");			// Level 17b)
	AddStringEntry("S_MUSICNAME28", "Slipping Slug\nby\nJoseph Collins");	// End Cheat
	AddStringEntry("S_MUSICNAME29", "Icy F 10rppq\nby\nkvee");				// Level 16b) / 22
	AddStringEntry("S_MUSICNAME30", "Too Hot\nby\nkvee");					// Level 10b)
	AddStringEntry("S_MUSICNAME31", "Nashville\nby\nKohntarkosz_");			// Level 1b)
	AddStringEntry("S_MUSICNAME32", "Mort Lab\nby\nMr.M");					// L24
	AddStringEntry("S_MUSICNAME33", "Mustard the Strength\nby\neggs_box");	// Level 15b)
	AddStringEntry("S_MUSICNAME34", "Blue Your Cover\nby\neggs_box");		// Level 15c)
	AddStringEntry("S_MUSICNAME35", "Mondo Green (Nisaba rmx)\nby\neggs_box"); // Level 15d)
	AddStringEntry("S_MUSICNAME36", "Jo Jackson\nby\nKohntarkosz_");		// End Minimum
	AddStringEntry("S_MUSICNAME37", "Bugs Will Bite\nby\neggs_box");		// End Minimum
	AddStringEntry("S_MUSICNAME38", "Yoshi's Hillville\nby\nTheBigV");		// Worldmap Bonus
	// (Note: only the name S_MUSICNAME0 is used directly by the game code, 
	//        the names for the other strings don't matter)
	
	// Bonus Level info
	AddStringEntry("S_BONUSLEVELINFO1", "Congrats!\nYou've scored\n500,000 points and\nunlocked your way to\nDonut Heaven. Enjoy!");
	AddStringEntry("S_BONUSLEVELINFO2", "Congrats!\nYou've scored over\n500,000 points and\nunlocked your way to\nDonut Heaven. Enjoy!");

	//CK_OBJ.C
	AddStringEntry("S_BADSTATE", "Object with bad state!");
	AddStringEntry("S_DOORTOOTALL", "Door too tall!");
	AddStringEntry("S_BADTURNTYPE", "Bad turn type!");
	AddStringEntry("S_BADOBCLASS_CUSTOM", "CK_CustomClipRects: Bad obclass");

	//CK_TEXT.C
	AddStringEntry("S_WORDLIMITEXCEEDED", "PageLayout: Word limit exceeded");
	AddStringEntry("S_BADTEXTSTART", "PageLayout: Text not headed with ^P");
	AddStringEntry("S_BADTEXTEND", "CacheLayoutGraphics: No ^E to terminate file!");
	AddStringEntry("S_PAGE", "pg ");
	AddStringEntry("S_OF", " of ");

	//CK_INTER.C
	AddStringEntry("S_BADSTARWARSLINE", "PrintStarWars: Line too long!");
	AddStringEntry("S_BADSTARWARSEND", "PrintStarWars: No ^ to terminate file!");

	//TODO: error messages in ID Engine parts of the code

	//ID_CA.C
	AddStringEntry("S_CANNOTOPEN", "Can't open ");
	AddStringEntry("S_DEBUGFILE", "DEBUG.TXT");
	AddStringEntry("S_CA_FARREAD", "CA_FarRead doesn't support 64K reads yet!");
	AddStringEntry("S_CA_FARWRITE", "CA_FarWrite doesn't support 64K reads yet!");
	AddStringEntry("S_BADSHIFTS", "CAL_CacheSprite: Bad shifts number!");
	AddStringEntry("S_BADMAP", "CA_CacheMap: Tried to load a non existent map!");
	AddStringEntry("S_CA_UPLEVEL", "CA_UpLevel: Up past level 7!");
	AddStringEntry("S_CA_DOWNLEVEL", "CA_DownLevel: Down past level 0!");
//	AddStringEntry("S_LOADING", "Loading");	
	// only required for thermometer loading screens

	//ID_IN.C
	AddStringEntry("S_NOJOYS", "nojoys");
	AddStringEntry("S_NOMOUSE", "nomouse");
	AddStringEntry("S_DEMOPLAYBACKEXCEEDED", "Demo playback exceeded");
	AddStringEntry("S_DEMOBUFFEROVERFLOW", "Demo buffer overflow");
	// keyboard key names: (do NOT change the order of these strings!)
	AddStringEntry("S_KEYNAME0", "");
	AddStringEntry("S_KEYNAME1", "Esc");
	AddStringEntry("S_KEYNAME2", "1");
	AddStringEntry("S_KEYNAME3", "2");
	AddStringEntry("S_KEYNAME4", "3");
	AddStringEntry("S_KEYNAME5", "4");
	AddStringEntry("S_KEYNAME6", "5");
	AddStringEntry("S_KEYNAME7", "6");
	AddStringEntry("S_KEYNAME8", "7");
	AddStringEntry("S_KEYNAME9", "8");
	AddStringEntry("S_KEYNAME10", "9");
	AddStringEntry("S_KEYNAME11", "0");
	AddStringEntry("S_KEYNAME12", "-");
	AddStringEntry("S_KEYNAME13", "+");
	AddStringEntry("S_KEYNAME14", "BkSp");
	AddStringEntry("S_KEYNAME15", "Tab");
	AddStringEntry("S_KEYNAME16", "Q");
	AddStringEntry("S_KEYNAME17", "W");
	AddStringEntry("S_KEYNAME18", "E");
	AddStringEntry("S_KEYNAME19", "R");
	AddStringEntry("S_KEYNAME20", "T");
	AddStringEntry("S_KEYNAME21", "Y");
	AddStringEntry("S_KEYNAME22", "U");
	AddStringEntry("S_KEYNAME23", "I");
	AddStringEntry("S_KEYNAME24", "O");
	AddStringEntry("S_KEYNAME25", "P");
	AddStringEntry("S_KEYNAME26", "[");
	AddStringEntry("S_KEYNAME27", "]");
	AddStringEntry("S_KEYNAME28", "Enter");
	AddStringEntry("S_KEYNAME29", "Ctrl");
	AddStringEntry("S_KEYNAME30", "A");
	AddStringEntry("S_KEYNAME31", "S");
	AddStringEntry("S_KEYNAME32", "D");
	AddStringEntry("S_KEYNAME33", "F");
	AddStringEntry("S_KEYNAME34", "G");
	AddStringEntry("S_KEYNAME35", "H");
	AddStringEntry("S_KEYNAME36", "J");
	AddStringEntry("S_KEYNAME37", "K");
	AddStringEntry("S_KEYNAME38", "L");
	AddStringEntry("S_KEYNAME39", ";");
	AddStringEntry("S_KEYNAME40", "\"");
	AddStringEntry("S_KEYNAME41", "~");
	AddStringEntry("S_KEYNAME42", "LShift");
	AddStringEntry("S_KEYNAME43", "?");
	AddStringEntry("S_KEYNAME44", "Z");
	AddStringEntry("S_KEYNAME45", "X");
	AddStringEntry("S_KEYNAME46", "C");
	AddStringEntry("S_KEYNAME47", "V");
	AddStringEntry("S_KEYNAME48", "B");
	AddStringEntry("S_KEYNAME49", "N");
	AddStringEntry("S_KEYNAME50", "M");
	AddStringEntry("S_KEYNAME51", ",");
	AddStringEntry("S_KEYNAME52", ".");
	AddStringEntry("S_KEYNAME53", "/");
	AddStringEntry("S_KEYNAME54", "RShift");
	AddStringEntry("S_KEYNAME55", "Num*");
	AddStringEntry("S_KEYNAME56", "Alt");
	AddStringEntry("S_KEYNAME57", "Space");
	AddStringEntry("S_KEYNAME58", "CapsLk");
	AddStringEntry("S_KEYNAME59", "F1");
	AddStringEntry("S_KEYNAME60", "F2");
	AddStringEntry("S_KEYNAME61", "F3");
	AddStringEntry("S_KEYNAME62", "F4");
	AddStringEntry("S_KEYNAME63", "F5");
	AddStringEntry("S_KEYNAME64", "F6");
	AddStringEntry("S_KEYNAME65", "F7");
	AddStringEntry("S_KEYNAME66", "F8");
	AddStringEntry("S_KEYNAME67", "F9");
	AddStringEntry("S_KEYNAME68", "F10");
	AddStringEntry("S_KEYNAME69", "NumLk");
	AddStringEntry("S_KEYNAME70", "ScrlLk");
	AddStringEntry("S_KEYNAME71", "Home");
	AddStringEntry("S_KEYNAME72", "Up");
	AddStringEntry("S_KEYNAME73", "PgUp");
	AddStringEntry("S_KEYNAME74", "Num-");
	AddStringEntry("S_KEYNAME75", "Left");
	AddStringEntry("S_KEYNAME76", "Num5");
	AddStringEntry("S_KEYNAME77", "Right");
	AddStringEntry("S_KEYNAME78", "Num+");
	AddStringEntry("S_KEYNAME79", "End");
	AddStringEntry("S_KEYNAME80", "Down");
	AddStringEntry("S_KEYNAME81", "PgDn");
	AddStringEntry("S_KEYNAME82", "Ins");
	AddStringEntry("S_KEYNAME83", "Del");
	AddStringEntry("S_KEYNAME84", "SysReq");
	AddStringEntry("S_KEYNAME85", "55h");
	AddStringEntry("S_KEYNAME86", "56h");
	AddStringEntry("S_KEYNAME87", "F11");
	AddStringEntry("S_KEYNAME88", "F12");
	AddStringEntry("S_LASTKEYNAME", "???");
	// (Note: only S_KEYNAME0 and S_LASTKEYNAME are used directly by the game code, 
	//        the other names don't matter)

	//ID_MM.C
	AddStringEntry("S_NOEMS", "noems");
	AddStringEntry("S_NOXMS", "noxms");
	AddStringEntry("S_NOUMB", "noumb");
	AddStringEntry("S_SETUPEMSERROR", "MML_SetupEMS: EMS error 0x");
	AddStringEntry("S_FREEEMSERROR", "MML_ShutdownEMS: Error freeing EMS!");
	AddStringEntry("S_MAPEMSERROR", "MM_MapEMS: EMS error 0x");
	AddStringEntry("S_SEGMENTSPANSBLOCKS", "MML_UseSpace: Segment spans two blocks!");
	AddStringEntry("S_NOPURGABLEBLOCKS", "MM_ClearBlock: No purgable blocks!");
	AddStringEntry("S_OUTOFMEMORY", "MM_GetPtr: Out of memory!");
	AddStringEntry("S_FREEPTR_BLOCKNOTFOUND", "MM_FreePtr: Block not found!");
	AddStringEntry("S_GETSIZE_BLOCKNOTFOUND", "MM_GetSize: Block not found!");
	AddStringEntry("S_SETPURGE_BLOCKNOTFOUND", "MM_SetPurge: Block not found!");
	AddStringEntry("S_SETLOCK_BLOCKNOTFOUND", "MM_SetLock: Block not found!");
	AddStringEntry("S_SETLOCK_BADTYPE", "MM_SetLock: Unhandled lock type");
	AddStringEntry("S_BLOCKORDERCORRUPTED", "MM_ShowMemory: Memory block order currupted!");

	//ID_RF.C
	AddStringEntry("S_MAPTOOTALL", "RF_NewMap: Map too tall!");
	AddStringEntry("S_BADBACKANIM", "RF_MarkTileGraphics: Background anim of 0:");
	AddStringEntry("S_TOOMANYANIMS", "RF_MarkTileGraphics: Too many unique animated tiles!");
	AddStringEntry("S_UNENDINGBACKANIM", "RF_MarkTileGraphics: Unending background animation:");
	AddStringEntry("S_BADFOREANIM", "RF_MarkTileGraphics: Foreground anim of 0:");
	AddStringEntry("S_UNENDINGFOREANIM", "RF_MarkTileGraphics: Unending foreground animation:");
	AddStringEntry("S_NOFREETILESPOTS", "RF_CheckForAnimTile: No free spots in tilearray!");
	AddStringEntry("S_TILEOUTOFBOUNDS", "RFL_AnimateTiles: Out of bounds!");
	AddStringEntry("S_TOOMANYHSCROLLBLOCKS", "RF_SetScrollBlock: Too many horizontal scroll blocks");
	AddStringEntry("S_TOOMANYVSCROLLBLOCKS", "RF_SetScrollBlock: Too many vertical scroll blocks");
	AddStringEntry("S_BADNEWROWDIR", "RFL_NewRow: Bad dir!");
	AddStringEntry("S_NOFREESPRITESPOTS", "RF_PlaceSprite: No free spots in spritearray!");
	AddStringEntry("S_UNCACHEDSPRITE", "RF_PlaceSprite: Placed an uncached sprite:");

	//ID_SD.C	
	AddStringEntry("S_NOAL", "NOAL");
	AddStringEntry("S_ADLIB", "ADLIB");
	AddStringEntry("S_OPLPORT", "OPLPORT");
	AddStringEntry("S_BADINSTRUMENT", "SDL_ALPlaySound() - Bad instrument");
	AddStringEntry("S_UNCACHEDSOUND", "SD_PlaySound() - Uncached sound");
	AddStringEntry("S_ZEROLENGTHSOUND", "SD_PlaySound() - Zero length sound");

	//ID_US_1.C
	AddStringEntry("S_COMP", "COMP");
	AddStringEntry("S_NOCOMP", "NOCOMP");
	AddStringEntry("S_JERK", "JERK");
	AddStringEntry("S_TEDLEVEL", "TEDLEVEL");
	AddStringEntry("S_NOWAIT", "NOWAIT");
	AddStringEntry("S_BADTEDLEVEL", "TEDLEVEL parameter must be followed by non-zero level number!");
	AddStringEntry("S_EMPTY", "Empty");
	AddStringEntry("S_SVGACOMPENABLED", "SVGA Compatibility Mode Enabled.");
	AddStringEntry("S_STARTUP_LOADING", "  Loading...   ");
	AddStringEntry("S_STARTUP_READY", " Ready - Press a Key     ");
	AddStringEntry("S_STRINGEXCEEDSWIDTH", "US_CPrintLine() - String exceeds width");

	//ID_US_2.C
	//TODO: not a lot we can do here without rewriting massive parts of ID_US_2...
	AddStringEntry("S_DEBUG", "DEBUG");
	AddStringEntry("S_NOSOUNDEFFECTS", "NO SOUND EFFECTS");
	AddStringEntry("S_PCSPEAKER", "PC SPEAKER");
	AddStringEntry("S_ADLIBSOUNDBLASTER", "ADLIB/SOUNDBLASTER");
	AddStringEntry("S_NOMUSIC", "NO MUSIC");
	AddStringEntry("S_BEGINEASYGAME", "BEGIN EASY GAME");
	AddStringEntry("S_BEGINNORMALGAME", "BEGIN NORMAL GAME");
	AddStringEntry("S_BEGINHARDGAME", "BEGIN HARD GAME");
		
		
	AddStringEntry("S_SCOREBOX", "SCORE BOX");
	AddStringEntry("S_SVGACOMPATIBILITY", "SVGA COMPATIBILITY");
	AddStringEntry("S_FIXJERKYMOTION", "FIX JERKY MOTION");
	AddStringEntry("S_TWOBUTTONFIRING", "TWO-BUTTON FIRING");
	AddStringEntry("S_MAXIMUMFRAMERATE", "MAXIMUM FRAME RATE");
	AddStringEntry("S_PAYTOSAVE", "PAY-TO-SAVE");
	AddStringEntry("S_QUICKLOAD", "QUICKLOAD");
	AddStringEntry("S_QUICKSAVE", "QUICKSAVE");
	AddStringEntry("S_UPLEFT", "UP & LEFT");
	AddStringEntry("S_UP", "UP");
	AddStringEntry("S_UPRIGHT", "UP & RIGHT");
	AddStringEntry("S_RIGHT", "RIGHT");
	AddStringEntry("S_DOWNRIGHT", "DOWN & RIGHT");
	AddStringEntry("S_DOWN", "DOWN");
	AddStringEntry("S_DOWNLEFT", "DOWN & LEFT");
	AddStringEntry("S_LEFT", "LEFT");
	AddStringEntry("S_JUMP", "JUMP");
	AddStringEntry("S_POGO", "POGO");
	AddStringEntry("S_FIRE", "FIRE");
	//new cutomizable buttons (scan, status, toggle score box)
	AddStringEntry("S_STATUS", "STATUS WINDOW");
	AddStringEntry("S_DETECTOR", "DETECTOR WINDOW");
	AddStringEntry("S_TOGGLESCOREBOX", "TOGGLE SCORE BOX");
	AddStringEntry("S_SAVEMENU", "SAVE MENU");
	AddStringEntry("S_LODAMENU", "LOAD MENU");
	//AddStringEntry("S_SUMMONDOPEFISH", "SUMMON DOPEFISH");
	AddStringEntry("S_MOVEMENT", "MOVEMENT");
	AddStringEntry("S_ACTIONBUTTONS", "ACTION BUTTONS");
	AddStringEntry("S_FUNCTIONBUTTONS", "FUNCTION BUTTONS");
	AddStringEntry("S_SOUND", "SOUND");
	AddStringEntry("S_MUSIC", "MUSIC");
	AddStringEntry("S_OPTIONS", "OPTIONS");
	AddStringEntry("S_USEKEYBOARD", "USE KEYBOARD");
	AddStringEntry("S_USEJOYSTICK1", "USE JOYSTICK #1");
	AddStringEntry("S_USEJOYSTICK2", "USE JOYSTICK #2");
	AddStringEntry("S_NEWGAME", "NEW GAME");
	AddStringEntry("S_LOADGAME", "LOAD GAME");
	AddStringEntry("S_SAVEGAME", "SAVE GAME");
	AddStringEntry("S_PADDLEWAR", "NIBBLES NOM NOM");
	AddStringEntry("S_HELPGAMEINFO", "HELP + GAME INFO");
	AddStringEntry("S_CONFIGURE", "CONFIGURE");
	AddStringEntry("S_QUIT1", "QUIT");
	AddStringEntry("S_EMPTYCOMM", "USL_ConfirmComm() - empty comm");
	AddStringEntry("S_ESCTOBACKOUT", "ESC TO BACK OUT");
	AddStringEntry("S_REALLYENDCURRENTGAME", "REALLY END CURRENT GAME?");
	AddStringEntry("S_PRESSYTOENDIT", "PRESS Y TO END IT");
	AddStringEntry("S_REALLYQUIT", "REALLY QUIT?");
	AddStringEntry("S_PRESSYTOQUIT", "PRESS Y TO QUIT");
	AddStringEntry("S_YOUREINAGAME", "YOU'RE IN A GAME");
	AddStringEntry("S_PRESSYTOLOADGAME", "PRESS Y TO LOAD GAME");
	AddStringEntry("S_SAVINGWILLCOSTALIFE", "SAVING WILL COST A LIFE");
	AddStringEntry("S_PRESSYTOSAVE", "PRESS Y TO SAVE ANYWAY");
	AddStringEntry("S_PRESSYFORNEWGAME", "PRESS Y FOR NEW GAME");
	AddStringEntry("S_ON", "ON");
	AddStringEntry("S_OFF", "OFF");
	AddStringEntry("S_AUTO", "AUTO");
	AddStringEntry("S_CONFIRM", "CONFIRM");
	
		// joke key names (must start with S_JOKEKEYNAME1 and end with S_JOKEKEYNAMEEND)
	AddStringEntry("S_JOKEKEYNAME1",  "SUMMON DOPEFISH");
	AddStringEntry("S_JOKEKEYNAME2",  "USE PARENT MONITOR");
	AddStringEntry("S_JOKEKEYNAME3",  "EAT YOUR VEGGIES");
	AddStringEntry("S_JOKEKEYNAME4",  "PRAISE GANNALECH");
	AddStringEntry("S_JOKEKEYNAME5",  "ORDER GALACTIPOGO");
	AddStringEntry("S_JOKEKEYNAME6",  "CHECK KEENWIKI");
	AddStringEntry("S_JOKEKEYNAME7",  "CALL LT. BARKER");
	AddStringEntry("S_JOKEKEYNAME8",  "WEAR MINDBELT");
	AddStringEntry("S_JOKEKEYNAME9",  "SQUEEZE FOOBS");
	AddStringEntry("S_JOKEKEYNAME10", "PUT ON BIG V MEDAL");
	AddStringEntry("S_JOKEKEYNAME11", "TALK OMNISPEAK");
	AddStringEntry("S_JOKEKEYNAME12", "CALL 555 VITACORP");
	AddStringEntry("S_JOKEKEYNAME13", "THROW BOOBUS BOMB");
	AddStringEntry("S_JOKEKEYNAME14", "REPEL NISASI");	
	//AddStringEntry("S_JOKEKEYNAME", "");
	AddStringEntry("S_JOKEKEYNAMEEND", "LIKE SHARE SUBSCRIBE");
	// (Note: only S_JOKEKEYNAME1 and S_JOKEKEYNAMEEND are used directly by 
	//        the game code, the other names don't matter)
	
	// do NOT change the order of the S_FRAMERATE strings!
	AddStringEntry("S_FRAMERATE1", "70");
	AddStringEntry("S_FRAMERATE2", "35");
	AddStringEntry("S_FRAMERATE3", "23.3");
	AddStringEntry("S_FRAMERATE4", "17.5");
	AddStringEntry("S_FRAMERATE5", "14");
	// (Note: only S_FRAMERATE1 is used directly by the game code, 
	//        the other names don't matter)
	
	AddStringEntry("S_CONTROL", "CONTROL: ");
	// do NOT change the order of these strings:
	AddStringEntry("S_CONTROLNAME0", "KEYBOARD");
	AddStringEntry("S_KEYBOARD", "KEYBOARD");
	AddStringEntry("S_JOYSTICK1", "JOYSTICK #1");
	AddStringEntry("S_JOYSTICK2", "JOYSTICK #2");
	AddStringEntry("S_MOUSE", "MOUSE");
	// (Note: only S_CONTROLNAME0 is used directly by the game code, 
	//        the other names don't matter)
	AddStringEntry("S_KEYALREADYUSED", "Key already used");
	AddStringEntry("S_PRESSAKEY", "Press a key");
	AddStringEntry("S_CALIBMIN1", "Move Joystick to upper left");
	AddStringEntry("S_CALIBMIN2", "and press button #1");
	AddStringEntry("S_CALIBMAX1", "Move Joystick to lower right");
	AddStringEntry("S_CALIBMAX2", "and press button #2");
	AddStringEntry("S_CALIBFAILED", "JOYSTICK CALIBRATION FAILED!");
	AddStringEntry("S_USINGJOY1", "USING JOYSTICK #1");
	AddStringEntry("S_USINGJOY2", "USING JOYSTICK #2");
	AddStringEntry("S_PRESSANYKEY", "PRESS ANY KEY");
	AddStringEntry("S_LOADING", "Loading");
	AddStringEntry("S_SAVING", "Saving");
	AddStringEntry("S_TYPENAME", "Type name");
	AddStringEntry("S_ENTERACCEPTS", "Enter accepts");
	AddStringEntry("S_ARROWSMOVE", "Arrows move");
	AddStringEntry("S_ENTERSELECTS", "Enter selects");
	AddStringEntry("S_ESCBACK", "ESC to back out");
	AddStringEntry("S_ESCQUIT", "ESC to quit");
	
	// do NOT change the order of these strings:
	AddStringEntry("S_QUICKLOADTOP", "QuickLoad will load slot number ");
	AddStringEntry("S_QUICKSAVETOP", "QuickSave will save to slot number ");
	AddStringEntry("S_QUICKLOADBOT", "Really load this game (Y/N)?");
	AddStringEntry("S_QUICKSAVEBOT", "Really overwrite this game (Y/N)?");
	AddStringEntry("S_HINTDISABLECONFIRM", "Hint: This confirmation\ndialog can be disabled\nin the options menu.");
	
	// Paddle War strings:
	AddStringEntry("S_PWKEEN", "KEEN:");
	AddStringEntry("S_PWCOMP", "COMP:");
	AddStringEntry("S_PWWON", "You won!");
	AddStringEntry("S_PWLOST", "You lost!");
	
	// NomNom strings:
	AddStringEntry("S_NNSCORE", "SCORE:");
	AddStringEntry("S_NNBEST", "BEST:");
	
	// error strings: (do NOT change the order of these strings!)
	AddStringEntry("S_ERROR0",  "Error: Unknown");
	AddStringEntry("S_ERROR1",  "Error: Invalid function number");
	AddStringEntry("S_ERROR2",  "Error: No such file or directory");
	AddStringEntry("S_ERROR3",  "Error: Path not found");
	AddStringEntry("S_ERROR4",  "Error: Too many open files");
	AddStringEntry("S_ERROR5",  "Error: Permission denied");
	AddStringEntry("S_ERROR6",  "Error: Bad file number");
	AddStringEntry("S_ERROR7",  "Error: Memory arena trashed");
	AddStringEntry("S_ERROR8",  "Error: Not enough memory");
	AddStringEntry("S_ERROR9",  "Error: Invalid memory block address");
	AddStringEntry("S_ERROR10", "Error: Invalid environment");
	AddStringEntry("S_ERROR11", "Error: Invalid format");
	AddStringEntry("S_ERROR12", "Error: Invalid access code");
	AddStringEntry("S_ERROR13", "Error: Invalid data");
	AddStringEntry("S_ERROR14", "Error: Bad address");
	AddStringEntry("S_ERROR15", "Error: No such device");
	AddStringEntry("S_ERROR16", "Error: Attempted to remove current directory");
	AddStringEntry("S_ERROR17", "Error: Not same device");
	AddStringEntry("S_ERROR18", "Error: No more files");
	AddStringEntry("S_ERROR19", "Error: Invalid argument");
	AddStringEntry("S_ERROR20", "Error: Arg list too big");
	AddStringEntry("S_ERROR21", "Error: Exec format error");
	AddStringEntry("S_ERROR22", "Error: Cross-device link");
	AddStringEntry("S_ERROR23", "Error: Unknown");
	AddStringEntry("S_ERROR24", "Error: Unknown");
	AddStringEntry("S_ERROR25", "Error: Unknown");
	AddStringEntry("S_ERROR26", "Error: Unknown");
	AddStringEntry("S_ERROR27", "Error: Unknown");
	AddStringEntry("S_ERROR28", "Error: Unknown");
	AddStringEntry("S_ERROR29", "Error: Unknown");
	AddStringEntry("S_ERROR30", "Error: Unknown");
	AddStringEntry("S_ERROR31", "Error: Unknown");
	AddStringEntry("S_ERROR32", "Error: Unknown");
	AddStringEntry("S_ERROR33", "Error: Math argument");
	AddStringEntry("S_ERROR34", "Error: Result too large");
	AddStringEntry("S_ERROR35", "Error: File already exists");
	AddStringEntry("S_ERROR36", "Error: Possible deadlock");
	AddStringEntry("S_ERRORDISKFULL",  "Error: Disk is Full");
	AddStringEntry("S_ERRORINCOMPLETE",  "Error: File is Incomplete");
	// (Note: only S_ERROR0, S_ERRORDISKFULL and S_ERRORINCOMPLETE are used 
	//        directly by the game code, the other names don't matter)
	
	AddStringEntry("S_NILCARD", "USL_DownLevel() - nil card");
	AddStringEntry("S_RETURNTOGAME", "RETURN TO GAME");
	AddStringEntry("S_RETURNTODEMO", "RETURN TO DEMO");
	AddStringEntry("S_VIEWSCORES", "VIEW SCORES");
	AddStringEntry("S_ENDGAME", "END GAME");
	AddStringEntry("S_CONTROLPANEL", "Control Panel");
	AddStringEntry("S_UNKNOWNCOMM", "USL_HandleComm() - unknown");
	AddStringEntry("S_QUITTING", "Quitting...");

	//ID_VW.C
	AddStringEntry("S_HIDDENCARD", "HIDDENCARD");
	AddStringEntry("S_NOBORDER", "NOBORDER");
	AddStringEntry("S_VGA", "VGA");
	AddStringEntry("S_IMPROPERCARD", "Improper video card!  If you really have an EGA card that I am not detecting,\n"
	  "use the -HIDDENCARD command line parameter (or use -VGA if you have a VGA card)!");

	SaveHeaderFile("..\\GAMESTR.H");
	SaveStringFile("..\\..\\GAMESTR.CKS");
	
	}
